spring:
  datasource:
    url: jdbc:mysql://localhost/aws-local-s3
    username: chris
    password: Chris@24
  jpa:
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB